name: test-remodel
base: core18
version: '1'
summary: test a remodel
description: Remodel from the snapd api

grade: devel
confinement: strict

apps:
  list:
    command: bin/list
    plugs: [ snapd-control, network, system-backup ]

parts:
  snapdapi:
    source: .
    plugin: go
    go-importpath: github.com/knitzsche/test-remodel
    build-packages: [ gcc ]
