name: test-snapdapi
base: core20
version: '1'
summary: test snapd rest api
description: snap rest api test

grade: stable
confinement: strict

apps:
  model:
    command: bin/model
    plugs: [ snapd-control, network, system-backup ]
  remodel:
    command: bin/remodel
    plugs: [ snapd-control, network, system-backup, home ]
  snap:
    command: bin/snap
    plugs: [ snapd-control, network, system-backup ]
  updates-neeeded:
    command: bin/updates-needed
    plugs: [ snapd-control, network, system-backup ]
  list:
    command: bin/list
    plugs: [ snapd-control, network, system-backup ]
  create-user:
    command: bin/createuser
    plugs: [ snapd-control, network, system-backup ]
  remove-user:
    command: bin/removeuser
    plugs: [ snapd-control, network, system-backup ]
  refresh-pending-for-snap:
    command: bin/snap-refresh-pending
    plugs: [ snapd-control, network, system-backup ]

# system-backup now seems needed to use snapd-control from snap CLI app.  
# see https://forum.snapcraft.io/t/possibly-missing-apparmor-network-permission/15054/

parts:
  snapdapi:
    source: .
    plugin: go
    build-packages: [ gcc ]
